name: Generate stats 
on:
  push:
jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install some extras
      run: |
        cd helpers
        git clone --branch version-2.03 https://github.com/IATI/IATI-Rulesets.git
        ln -s IATI-Rulesets/rulesets .
        ./get_codelist_mapping.sh
        ./get_codelists.sh
        ./get_schemas.sh
        wget -q "https://raw.githubusercontent.com/codeforIATI/IATI-Dashboard/main/registry_id_relationships.csv"
        cd ..
    - name: Download IATI data
      run: |
        wget -q -O iati_dump.zip https://gitlab.com/codeforIATI/iati-snapshot-mirror/-/archive/74b564ad42e8ec98f53a25fac78b95c09e952c33/iati-snapshot-mirror-74b564ad42e8ec98f53a25fac78b95c09e952c33.zip
        unzip -q iati-snapshot-mirror-74b564ad42e8ec98f53a25fac78b95c09e952c33.zip
        mv 74b564ad42e8ec98f53a25fac78b95c09e952c33 data
        rm -rf iati-snapshot-mirror-74b564ad42e8ec98f53a25fac78b95c09e952c33.zip
    - name: Checkout output
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        repository: codeforIATI/IATI-Stats-public
        path: out
    - name: Delete out/current
      run: rm -rf out/current
    - name: Generate ckan.json
      run: |
        python helpers/ckan.py
        cp ckan.json out
        mv ckan.json helpers
        mv metadata.json out
        mv licenses.json out
    - name: Run loop
      run: python calculate_stats.py --output out/current loop
    - name: Delete data and metadata
      run: rm -rf data metadata
    - name: Run aggregate
      run: python calculate_stats.py --output out/current aggregate
    - name: Run invert
      run: python calculate_stats.py --output out/current invert
    - name: Run gitaggregate
      run: python statsrunner/gitaggregate.py dated
    - name: Run gitaggregate-publisher
      run: python statsrunner/gitaggregate-publisher.py dated
    - name: Add static files to output
      run: cp -r static/* out
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        force_orphan: true
