name: Generate stats
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install some extras
      run: |
        cd helpers
        git clone --branch version-2.03 https://github.com/IATI/IATI-Rulesets.git
        ln -s IATI-Rulesets/rulesets .
        ./get_codelist_mapping.sh
        ./get_codelists.sh
        ./get_schemas.sh
        wget -q "https://raw.githubusercontent.com/codeforIATI/IATI-Dashboard/main/registry_id_relationships.csv"
        cd ..
    - name: Download IATI data
      run: |
        wget -q -O iati_dump.zip https://gitlab.com/codeforIATI/iati-data/-/archive/main/iati-data-main.zip
        unzip -q iati_dump.zip
        rm -rf iati_dump.zip
    - name: Checkout output
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        repository: codeforIATI/IATI-Stats-public
        path: out
    - name: Delete out/current
      run: rm -rf out/current
    - name: Generate ckan.json
      run: |
        python helpers/ckan.py
        cp ckan.json out
        mv ckan.json helpers
        mv metadata.json out
        mv licenses.json out
    - name: Run loop
      run: python calculate_stats.py --output out/current loop
    - name: Delete data and metadata
      run: rm -rf data metadata
    - name: Run aggregate
      run: python calculate_stats.py --output out/current aggregate
    - name: Run invert
      run: python calculate_stats.py --output out/current invert
    - name: Run gitaggregate
      run: python statsrunner/gitaggregate.py dated
    - name: Run gitaggregate-publisher
      run: python statsrunner/gitaggregate-publisher.py dated
    - name: Add static files to output
      run: cp -r static/* out
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GIT_CONFIG_NAME: Code for IATI bot
        GIT_CONFIG_EMAIL: 57559326+codeforIATIbot@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPOSITORY_NAME: codeforIATI/IATI-Stats-public
        BRANCH: gh-pages
        FOLDER: out
        CLEAN: true
    - name: Trigger a build on the analytics repo
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: codeforIATI/analytics
        token: ${{ secrets.TOKEN }}
        event-type: build
