name: Generate stats
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  generate_stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Cache dependencies
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Install some extras
      run: |
        cd helpers
        git clone --branch version-2.03 https://github.com/IATI/IATI-Rulesets.git
        ln -s IATI-Rulesets/rulesets .
        ./get_codelist_mapping.sh
        ./get_codelists.sh
        ./get_schemas.sh
        wget -q "http://dashboard.iatistandard.org/stats/ckan.json"
        wget -q "https://raw.githubusercontent.com/codeforIATI/IATI-Dashboard/main/registry_id_relationships.csv"
        cd ..
    - name: Download IATI data
      run: |
        wget -q -O iati_dump.zip https://www.dropbox.com/s/kkm80yjihyalwes/iati_dump.zip?dl=1
        unzip -q iati_dump.zip
        rm -rf iati_dump.zip metadata metadata.json
    - name: Run loop
      run: python calculate_stats.py loop
    - name: Run aggregate
      run: python calculate_stats.py aggregate
    - name: Run invert
      run: python calculate_stats.py invert
    - name: Add CNAME to output
      run: echo "dashboard-stats.codeforiati.org" > out/CNAME
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GIT_CONFIG_NAME: Code for IATI bot
        GIT_CONFIG_EMAIL: 57559326+codeforIATIbot@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
        CLEAN: true
